# Generated by Django 3.1.4 on 2020-12-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CAMPAIGN AGAINST GENOCIDE', 'CAMPAIGN AGAINST GENOCIDE'), ('RWANDA ART', 'RWANDA ART'), ("KING'S PALACE", "KING'S PALACE"), ('NATIONAL LIBERATION', 'NATIONAL LIBERATION'), ('ENVIRONMENT', 'ENVIRONMENT'), ('KWIGIRA', 'KWIGIRA'), ("KANDT'S HOUSE", "KANDT'S HOUSE"), ('ETHNOGRAPHIC', 'ETHNOGRAPHIC')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/museums')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
