# Generated by Django 3.1.4 on 2021-01-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20210102_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='museum',
        ),
    ]
