# Generated by Django 3.1.4 on 2021-01-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_booking_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='price',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
